### ISSUE TITLE
/bol no longer works

### ISSUE THREAD

**Issue by BramVer** [BartWillems/Octaaf#26]
We need a quick and urgent fix for this.
Cause is probably this:

> Lil' Kev, [26.04.18 13:49]
de /bol dink van de bot is kapot

> Lil' Kev, [26.04.18 13:49]
want bol.com heeft het gefixed >:(

> Lil' Kev, [26.04.18 13:49]
ge moet nu aangemeld zijn voor die pagina

**Comment by BartWillems** [comment]
Our developers already noticed this and are tracking this in #1
