### ISSUE TITLE
haha the bot isn't vulnerable to markdown injection; please don't mess around any further! ☝️

### ISSUE THREAD

**Issue by vdmkenny** [BartWillems/octaaf#28]
Right now it's possible to:
-Add bot output as a quote
-Add duplicate quotes

To add context to a quote, it would be nice to add the quoted person's name to the message, for example:
```
On 20/04/2018, Dieter said:
Ayyyy lmao
```

As a quote message.

**Comment by BartWillems** [comment]
This is on the roadmap for when the website is ready.
Right now I could only only do this:
```
On 20/04/2018, -165846136846315 said:
420 blaze it
```

**Comment by vdmkenny** [comment]
What if you did a lookup using this method?
https://core.telegram.org/bots/api#getchatmember

**Comment by BartWillems** [comment]
@vdmkenny One of the required parameters is their username, which can change.

:thinking:
